### PR TITLE
code for redirect

### PR DESCRIPTION
**Pull request by meeki007**
allows you to redirect a user to a URL

### CODE REVIEW

**Comment by dceejay** [comment]
how does this behave when used in a ui_worldmap node ? (ie in dashboard) - does it redirect whole page - or just the iframe ?

**Comment by meeki007** [comment]
Good call. I never use the ui_worldmap node. It is a mess. Hold off on merge. I need to decided if I'm going to fix it or disable the functionality when using inside of ui_node

**Comment by meeki007** [comment]
Working on issue today.   Took me awhile to wrap my head around the 
https://github.com/dceejay/RedMap/blob/master/worldmap.js
as ive spent most my time in the land of the
https://github.com/dceejay/RedMap/blob/master/worldmap/worldmap.js

I see how function HTML works with ui_worldmap

going to use something like 

```
if (msg.hasOwnProperty("payload") && msg.payload.hasOwnProperty("command") && msg.payload.command.hasOwnProperty("redirect"))
```

then I can cause the same effect on the ui_worldmap dashboard  ..... I think.

This project is not as dead as I thought.

**Comment by meeki007** [comment]
Working on issue today.   
```
if (msg.hasOwnProperty("payload") && msg.payload.hasOwnProperty("command") && msg.payload.command.hasOwnProperty("clear"))
```

**Comment by meeki007** [comment]
Need some help when you find time.
So I got to thinking it would be real nice if I only had to change one area of the code to get this to work.
https://github.com/dceejay/RedMap/blob/master/worldmap.js line 148

I am trying this but I just cant get it to work
```
var html = `<script> (function(scope) {
            scope.$watch('msg', function(msg) {
                if (msg.hasOwnProperty("payload") && msg.payload.hasOwnProperty("command") && msg.payload.command.hasOwnProperty("redirect")) {
                    window.location.href = cmd.redirect;
                }
            });
        })(scope); </script>
        <style>.nr-dashboard-ui_worldmap{padding:0;}</style><div style="overflow:hidden;">
        <iframe src="${url}" width="${frameWidth}px" height="${frameHeight}px" style="border:none;"></iframe>
        </div>`;
        return html;
```

Ive stuck in just:
```
<script>
window.location.href = "https://nodered.org";
</script>
```
and that works fine. 
Care to point me in a direction ?

**Pull request closed without merging**
