### PR TITLE
Basic Dynamic Search Control using the command

### PR DESCRIPTION
**Pull request by RohanAsmat**
Search using a search command:
msg.payload = { command:{search:"us10"} };

and clearing it using the following:
msg.payload = { command:{search:"clear"} };

### CODE REVIEW

**Comment by dceejay** [comment]
Hi apologies - didn't know you were going to do this directly - so the package.json has moved on already :-)... best not to edit versions in there.
Also index.html has also been updated more recently.

**Comment by RohanAsmat** [comment]
Hi @dceejay,

I have update the fork with the requested and reviewed changes! 


Best,
Muhammad Rohan Ali Asmat

**Comment by dceejay** [comment]
Looks good - will check it more thoroughly tomorrow then release.

Many thanks for you contribution.

**Comment by dceejay** [comment]
Hi - looking at it some more - I have changed the clear to be an empty string "" and added a check to see that the search is a string. Pushed to master - not quite released. :-)

**Comment by dceejay** [comment]
Long as it works for you will push it out now

**Comment by RohanAsmat** [comment]
Great! Many Thanks!

**Pull request merged**
